package com.example.messaging

import android.content.Context
import com.example.messaging.callbacks.MessageCallback
import com.tencent.imsdk.v2.*

/**
 * MessagingManager - A wrapper around Tencent IM SDK for messaging operations
 *
 * Usage:
 * 1. Initialize SDK: MessagingManager.initialize(context, sdkAppId, config)
 * 2. Login: MessagingManager.login(userId, userSig, callback)
 * 3. Send messages: sendTextMessage(), sendImageMessage(), sendFileMessage()
 * 4. Logout: MessagingManager.logout()
 */
object MessagingManager {

    private var isInitialized = false
    private var sdkListener: V2TIMSDKListener? = null

    /**
     * Initialize the Tencent IM SDK
     *
     * @param context Application context
     * @param sdkAppId Your Tencent IM SDK App ID
     * @param listener Optional SDK connection listener
     * @return true if initialization succeeded, false otherwise
     */
    fun initialize(
        context: Context,
        sdkAppId: Int,
        listener: V2TIMSDKListener? = null
    ): Boolean {
        if (isInitialized) {
            return true
        }

        val config = V2TIMSDKConfig().apply {
            logLevel = V2TIMSDKConfig.V2TIM_LOG_DEBUG
        }

        sdkListener = listener

        val success = V2TIMManager.getInstance().initSDK(
            context,
            sdkAppId,
            config,
            listener
        )

        isInitialized = success
        return success
    }

    /**
     * Login to Tencent IM
     *
     * @param userId User ID
     * @param userSig User signature (generated by your backend)
     * @param callback Callback for login result
     */
    fun login(userId: String, userSig: String, callback: MessageCallback) {
        if (!isInitialized) {
            callback.onError(-1, "SDK not initialized. Call initialize() first.")
            return
        }

        V2TIMManager.getInstance().login(userId, userSig, object : V2TIMCallback {
            override fun onSuccess() {
                callback.onSuccess(null)
            }

            override fun onError(code: Int, desc: String?) {
                callback.onError(code, desc)
            }
        })
    }

    /**
     * Logout from Tencent IM
     *
     * @param callback Callback for logout result
     */
    fun logout(callback: MessageCallback) {
        V2TIMManager.getInstance().logout(object : V2TIMCallback {
            override fun onSuccess() {
                callback.onSuccess(null)
            }

            override fun onError(code: Int, desc: String?) {
                callback.onError(code, desc)
            }
        })
    }

    /**
     * Send a text message
     *
     * @param targetUserId Recipient user ID
     * @param text Message text
     * @param callback Callback for send result
     */
    fun sendTextMessage(
        targetUserId: String,
        text: String,
        callback: MessageCallback
    ) {
        if (!isInitialized) {
            callback.onError(-1, "SDK not initialized. Call initialize() first.")
            return
        }

        val message = V2TIMManager.getMessageManager().createTextMessage(text)

        V2TIMManager.getMessageManager().sendMessage(
            message,
            targetUserId,
            null,
            V2TIMMessage.V2TIM_PRIORITY_NORMAL,
            false,
            null,
            object : V2TIMSendCallback<V2TIMMessage> {
                override fun onProgress(progress: Int) {
                    callback.onProgress(progress)
                }

                override fun onSuccess(msg: V2TIMMessage?) {
                    callback.onSuccess(msg?.msgID)
                }

                override fun onError(code: Int, desc: String?) {
                    callback.onError(code, desc)
                }
            }
        )
    }

    /**
     * Send an image message
     *
     * @param targetUserId Recipient user ID
     * @param imagePath Local file path to the image
     * @param callback Callback for send result
     */
    fun sendImageMessage(
        targetUserId: String,
        imagePath: String,
        callback: MessageCallback
    ) {
        if (!isInitialized) {
            callback.onError(-1, "SDK not initialized. Call initialize() first.")
            return
        }

        val message = V2TIMManager.getMessageManager().createImageMessage(imagePath)

        V2TIMManager.getMessageManager().sendMessage(
            message,
            targetUserId,
            null,
            V2TIMMessage.V2TIM_PRIORITY_NORMAL,
            false,
            null,
            object : V2TIMSendCallback<V2TIMMessage> {
                override fun onProgress(progress: Int) {
                    callback.onProgress(progress)
                }

                override fun onSuccess(msg: V2TIMMessage?) {
                    callback.onSuccess(msg?.msgID)
                }

                override fun onError(code: Int, desc: String?) {
                    callback.onError(code, desc)
                }
            }
        )
    }

    /**
     * Send a file message
     *
     * @param targetUserId Recipient user ID
     * @param filePath Local file path
     * @param fileName Optional file name (empty string for auto-detect)
     * @param callback Callback for send result
     */
    fun sendFileMessage(
        targetUserId: String,
        filePath: String,
        fileName: String = "",
        callback: MessageCallback
    ) {
        if (!isInitialized) {
            callback.onError(-1, "SDK not initialized. Call initialize() first.")
            return
        }

        val message = V2TIMManager.getMessageManager().createFileMessage(filePath, fileName)

        V2TIMManager.getMessageManager().sendMessage(
            message,
            targetUserId,
            null,
            V2TIMMessage.V2TIM_PRIORITY_NORMAL,
            false,
            null,
            object : V2TIMSendCallback<V2TIMMessage> {
                override fun onProgress(progress: Int) {
                    callback.onProgress(progress)
                }

                override fun onSuccess(msg: V2TIMMessage?) {
                    callback.onSuccess(msg?.msgID)
                }

                override fun onError(code: Int, desc: String?) {
                    callback.onError(code, desc)
                }
            }
        )
    }

    /**
     * Get the currently logged in user ID
     *
     * @return Current user ID or null if not logged in
     */
    fun getCurrentUserId(): String? {
        return V2TIMManager.getInstance().loginUser
    }

    /**
     * Check if SDK is initialized
     */
    fun isInitialized(): Boolean = isInitialized

    /**
     * Get direct access to Tencent SDK Manager (for advanced usage)
     */
    fun getSDKManager(): V2TIMManager {
        return V2TIMManager.getInstance()
    }

    /**
     * Get direct access to Message Manager (for advanced usage)
     */
    fun getMessageManager(): V2TIMMessageManager {
        return V2TIMManager.getMessageManager()
    }

    /**
     * Get direct access to Conversation Manager (for advanced usage)
     */
    fun getConversationManager(): V2TIMConversationManager {
        return V2TIMManager.getConversationManager()
    }
}
